import { seedImage, seedImages } from "./images";
const now = "2026-03-28T12:00:00.000Z";
/**
 * The cohort. Names are deliberately multi-regional; nicknames are the kind a
 * group actually assigns — earned from one specific incident, not descriptive.
 */
export const people = [
    {
        id: "p-amara",
        slug: "amara-reddy",
        name: "Amara Reddy",
        role: "Trainee — Backend",
        department: "Platform Engineering",
        nickname: "The Debugger",
        favoriteQuote: "It's never the compiler. It's you. It's always you.",
        bestMemory: "2am on November 14th, when the build finally went green and eleven people screamed in a room meant for silent study.",
        bio: "Arrived knowing exactly one language and left reviewing everyone else's pull requests. Kept a running tally of production incidents on a sticky note above her monitor. It reached forty-one.",
        avatar: seedImage("person-amara", { width: 800, height: 800, label: "Amara" }),
        gallery: seedImages(["amara-1", "amara-2", "amara-3"], { label: "Amara" }),
        achievements: [
            "Hackathon winner — Best Backend",
            "41 production incidents survived",
            "Wrote the onboarding doc everyone still uses",
        ],
        period: "11.2025 → 03.2026",
        funFact: "Cannot start work without exactly one and a half cups of coffee.",
        favoriteMemoryId: "m-first-green-build",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "p-tobias",
        slug: "tobias-lindqvist",
        name: "Tobias Lindqvist",
        role: "Trainee — Frontend",
        department: "Product Engineering",
        nickname: "Pixel",
        favoriteQuote: "Move it two pixels left. No — my left.",
        bestMemory: "Redesigning the entire demo UI four hours before judging, because someone said it looked 'fine'.",
        bio: "Could not walk past a misaligned button. Spent an entire lunch break arguing about border radius and won, decisively, with a printout.",
        avatar: seedImage("person-tobias", { width: 800, height: 800, label: "Tobias" }),
        gallery: seedImages(["tobias-1", "tobias-2"], { label: "Tobias" }),
        achievements: ["Design system author", "Hackathon winner — Best UI"],
        period: "11.2025 → 03.2026",
        funFact: "Owns nine identical grey shirts. Claims it's a productivity strategy.",
        favoriteMemoryId: "m-hackathon-night",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "p-ifeoma",
        slug: "ifeoma-okafor",
        name: "Ifeoma Okafor",
        role: "Trainee — Data",
        department: "Analytics",
        nickname: "The Oracle",
        favoriteQuote: "The data already told you. You just didn't like the answer.",
        bestMemory: "The Thursday she presented three months of churn analysis and the room went completely silent for eight seconds.",
        bio: "Turned every casual question into a dashboard. Nobody asked her to. Everybody used them.",
        avatar: seedImage("person-ifeoma", { width: 800, height: 800, label: "Ifeoma" }),
        gallery: seedImages(["ifeoma-1", "ifeoma-2"], { label: "Ifeoma" }),
        achievements: ["Built the cohort dashboard", "Certificate — Advanced SQL"],
        period: "11.2025 → 03.2026",
        funFact: "Has strong, well-researched opinions about spreadsheet fonts.",
        favoriteMemoryId: "m-demo-day",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "p-rafael",
        slug: "rafael-monteiro",
        name: "Rafael Monteiro",
        role: "Trainee — Full Stack",
        department: "Product Engineering",
        nickname: "Sunrise",
        favoriteQuote: "We can sleep after the demo.",
        bestMemory: "Watching the sun come up over the parking structure with four other people and a laptop that was still compiling.",
        bio: "The last one out of the building, every single week. Not because he was slow — because he kept helping.",
        avatar: seedImage("person-rafael", { width: 800, height: 800, label: "Rafael" }),
        gallery: seedImages(["rafael-1", "rafael-2", "rafael-3"], { label: "Rafael" }),
        achievements: ["Most pull request reviews", "Hackathon — Team lead"],
        period: "11.2025 → 03.2026",
        funFact: "Brought homemade pão de queijo every Friday. Never explained why.",
        favoriteMemoryId: "m-sunrise-parking",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "p-mei",
        slug: "mei-tanaka",
        name: "Mei Tanaka",
        role: "Trainee — QA",
        department: "Quality Engineering",
        nickname: "Breaker",
        favoriteQuote: "I found another one. You're going to hate it.",
        bestMemory: "Breaking the flagship feature in under ninety seconds during the dry run, and being thanked for it.",
        bio: "Approached every build like a personal challenge. Holds the unofficial cohort record: seventeen bugs in one afternoon.",
        avatar: seedImage("person-mei", { width: 800, height: 800, label: "Mei" }),
        gallery: seedImages(["mei-1", "mei-2"], { label: "Mei" }),
        achievements: ["17 bugs in one session", "Certificate — Test Automation"],
        period: "11.2025 → 03.2026",
        funFact: "Keeps a notebook titled 'Things That Should Not Have Worked'.",
        favoriteMemoryId: "m-bug-hunt",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "p-david",
        slug: "david-oyelaran",
        name: "David Oyelaran",
        role: "Trainee — Cloud",
        department: "Infrastructure",
        nickname: "Terraform",
        favoriteQuote: "It works on my machine is not a deployment strategy.",
        bestMemory: "The first time a deploy went out with nobody watching it, and nothing broke.",
        bio: "Automated everything he touched, including the coffee order. The script had a config file. It had tests.",
        avatar: seedImage("person-david", { width: 800, height: 800, label: "David" }),
        gallery: seedImages(["david-1", "david-2"], { label: "David" }),
        achievements: ["Zero-downtime deploy pipeline", "Certificate — Cloud Practitioner"],
        period: "11.2025 → 03.2026",
        funFact: "His coffee-order script has more tests than most production code.",
        favoriteMemoryId: "m-first-deploy",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "p-sofia",
        slug: "sofia-marchetti",
        name: "Sofia Marchetti",
        role: "Trainee — Design",
        department: "Product Design",
        nickname: "Red Pen",
        favoriteQuote: "Make it simpler. Now make it simpler than that.",
        bestMemory: "The critique where she cut half her own presentation live, on stage, and it got better.",
        bio: "Removed more than she added, always. The cohort's slides improved measurably after she joined the review rotation.",
        avatar: seedImage("person-sofia", { width: 800, height: 800, label: "Sofia" }),
        gallery: seedImages(["sofia-1", "sofia-2"], { label: "Sofia" }),
        achievements: ["Ran weekly design critique", "Rebranded the cohort demo"],
        period: "11.2025 → 03.2026",
        funFact: "Sketches on actual paper. Photographs it. Never digitizes it.",
        favoriteMemoryId: "m-critique",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "p-arjun",
        slug: "arjun-nair",
        name: "Arjun Nair",
        role: "Trainee — Mobile",
        department: "Product Engineering",
        nickname: "Two Devices",
        favoriteQuote: "But does it work on the old Android?",
        bestMemory: "Testing the app on a nine-year-old phone he found in a drawer, and shipping the fix that came out of it.",
        bio: "Carried two phones and a tablet everywhere. Found the edge cases nobody else could reproduce.",
        avatar: seedImage("person-arjun", { width: 800, height: 800, label: "Arjun" }),
        gallery: seedImages(["arjun-1", "arjun-2"], { label: "Arjun" }),
        achievements: ["Shipped the mobile demo", "Certificate — Mobile Development"],
        period: "11.2025 → 03.2026",
        funFact: "Names every test device after a planet. The old Android is Pluto.",
        favoriteMemoryId: "m-team-lunch",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "p-lucia",
        slug: "lucia-fernandez",
        name: "Lucía Fernández",
        role: "Trainee — Security",
        department: "Platform Engineering",
        nickname: "Lockpick",
        favoriteQuote: "I got in through the search bar. Please fix the search bar.",
        bestMemory: "The security review where she demonstrated three vulnerabilities using only the demo app's own features.",
        bio: "Read the docs nobody reads. Filed the tickets nobody wanted. Every single one turned out to matter.",
        avatar: seedImage("person-lucia", { width: 800, height: 800, label: "Lucia" }),
        gallery: seedImages(["lucia-1", "lucia-2"], { label: "Lucia" }),
        achievements: ["Found 3 critical vulnerabilities", "Certificate — Security Fundamentals"],
        period: "11.2025 → 03.2026",
        funFact: "Genuinely reads the terms of service. All of them.",
        favoriteMemoryId: "m-security-review",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "p-kwame",
        slug: "kwame-mensah",
        name: "Kwame Mensah",
        role: "Trainee — Backend",
        department: "Platform Engineering",
        nickname: "Cache",
        favoriteQuote: "Why is it slow? It's always the N+1. It's the N+1 again.",
        bestMemory: "Cutting the dashboard load time from eleven seconds to four hundred milliseconds in one afternoon.",
        bio: "Obsessed with speed in a way that made everyone else's code faster too. Kept a leaderboard.",
        avatar: seedImage("person-kwame", { width: 800, height: 800, label: "Kwame" }),
        gallery: seedImages(["kwame-1", "kwame-2"], { label: "Kwame" }),
        achievements: ["27× dashboard speedup", "Hackathon winner — Best Backend"],
        period: "11.2025 → 03.2026",
        funFact: "Times his commute daily. Has a spreadsheet. Has a trend line.",
        favoriteMemoryId: "m-hackathon-night",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "p-priya",
        slug: "priya-sharma",
        name: "Priya Sharma",
        role: "Mentor — Engineering",
        department: "Platform Engineering",
        nickname: "The Compass",
        favoriteQuote: "I'm not going to tell you the answer. Ask me a better question.",
        bestMemory: "The morning the whole cohort solved a problem she'd deliberately left unsolved on the whiteboard.",
        bio: "Twelve years in, and still the first to admit when she didn't know something. Taught mostly by refusing to answer.",
        avatar: seedImage("person-priya", { width: 800, height: 800, label: "Priya" }),
        gallery: seedImages(["priya-1", "priya-2"], { label: "Priya" }),
        achievements: ["Mentored 23 trainees", "Designed the curriculum"],
        period: "11.2025 → 03.2026",
        funFact: "Her whiteboard was never erased. It became a monument.",
        favoriteMemoryId: "m-whiteboard",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: "p-henrik",
        slug: "henrik-solberg",
        name: "Henrik Solberg",
        role: "Mentor — Architecture",
        department: "Platform Engineering",
        nickname: "Slow Down",
        favoriteQuote: "You've written three hundred lines. Delete two hundred and eighty.",
        bestMemory: "Watching a trainee argue him out of his own architectural decision, correctly, with evidence.",
        bio: "Spoke rarely. When he did, people wrote it down. Had a gift for the one question that collapsed a bad design.",
        avatar: seedImage("person-henrik", { width: 800, height: 800, label: "Henrik" }),
        gallery: seedImages(["henrik-1", "henrik-2"], { label: "Henrik" }),
        achievements: ["Architecture review lead", "Mentored 4 cohorts"],
        period: "11.2025 → 03.2026",
        funFact: "Draws system diagrams exclusively in pencil. Erases constantly.",
        favoriteMemoryId: "m-architecture-review",
        createdAt: now,
        updatedAt: now,
    },
];
export const peopleById = new Map(people.map((p) => [p.id, p]));
export function personName(id) {
    return peopleById.get(id)?.name ?? "Unknown";
}
